name: Publish Ansible project
run-name: /#${{ github.run_number }} @ ${{ github.actor }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        run: ansible-playbook ./playbooks/pull-repo.yml
