name: Publish Ansible project
run-name: '${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}'

on:
  push:
    branches:
      - 'main'

jobs:
  setup-and-run-terraform:
    runs-on:
      - self-hosted
      - lab

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run ansible-setup.sh
      run: |
        chmod +x ./ansible-setup.sh
        ./ansible-setup.sh

    - name: Verify Ansible installation
      run: ansible --version
