name: Publish Ansible project
run-name: ${{ github.actor }} is deploying run ${{ github.run_number }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-and-run-terraform:
    runs-on: self-hosted

    steps:
      - name: Set up Terraform
        env:
          MKADMIN_LOGIN: ${{ vars.MKADMIN_LOGIN }}
          MKADMIN_PASSWORD: ${{ secrets.MKADMIN_PASSWORD }}
        run: |
          OS=$(uname | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          
          if [ "$ARCH" == "x86_64" ]; then
            ARCH="amd64"
          elif [[ "$ARCH" == "arm"* ]]; then
            ARCH="arm"
          fi

          if [[ "$OS" == "linux" ]]; then
            INSTALL_PATH="/opt/terraform"
            PROJECT_PATH="/usr/local/terraform"
          elif [[ "$OS" == "darwin" ]]; then
            INSTALL_PATH="/opt/terraform"
            PROJECT_PATH="/usr/local/terraform"
          elif [[ "$OS" == "mingw"* ]] || [[ "$OS" == "cygwin"* ]]; then
            INSTALL_PATH="D:/opt/terraform"
            PROJECT_PATH="D:/usr/local/terraform"
          else
            echo "OS not supported"
            exit 1
          fi

          if [ ! -f "$INSTALL_PATH/terraform" ]; then
            echo "Terraform not found. Downloading..."
            echo "${{ secrets.MKADMIN_PASSWORD }}" | su -c "mkdir -p $INSTALL_PATH" ${{ secrets.MKADMIN_LOGIN }}
            LATEST_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r .current_version)
            wget https://releases.hashicorp.com/terraform/${LATEST_VERSION}/terraform_${LATEST_VERSION}_${OS}_${ARCH}.zip
            echo "${{ secrets.MKADMIN_PASSWORD }}" | su -c "unzip terraform_${LATEST_VERSION}_${OS}_${ARCH}.zip -d $INSTALL_PATH" ${{ secrets.MKADMIN_LOGIN }}
            rm terraform_${LATEST_VERSION}_${OS}_${ARCH}.zip
            echo "Terraform downloaded and extracted to $INSTALL_PATH"
          else
            echo "Terraform already exists in $INSTALL_PATH"
          fi
          echo "${{ secrets.MKADMIN_PASSWORD }}" | su -c "ln -sf $INSTALL_PATH/terraform /usr/local/bin/terraform" ${{ secrets.MKADMIN_LOGIN }}
