name: Publish Ansible project
run-name: ${{ github.actor }} is deploying at (${{ github.run_number }})

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Ansible Playbook
        env:
          MKADMIN_LOGIN: ${{ vars.MKADMIN_LOGIN }}
          MKADMIN_PASSWORD: ${{ secrets.MKADMIN_PASSWORD }}
        run: ansible-playbook ./playbooks/pull-repo.yml -i ./inventory/hosts.ini -e MKADMIN_LOGIN=$MKADMIN_LOGIN -e MKADMIN_PASSWORD=$MKADMIN_PASSWORD
