name: Publish Ansible project
run-name: ${{ github.actor }}/${{ github.action }}@${{ github.run_number }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible using apt-get
        run: |
          apt-get update
          apt-get install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook pull-repo.yml
